### ISSUE TITLE
Please mention somewhere in the readme what firefox-greenlight-tests are used for

### ISSUE THREAD

**Issue by mwargers** [mozilla/firefox-ui-tests#28]
The readme doc on github doesn't mention at all what these firefox-greenlight-tests are doing.
They should at least mention that they are used to run browser desktop UI tests (and perhaps also that they are meant to replace Mozmill).

**Comment by whimboo** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1121712 for this request.
