### ISSUE TITLE
Integrate greenlight libs with marionette after bug 941749

### ISSUE THREAD

**Issue by chmanchester** [mozilla/firefox-ui-tests#29]
https://bugzilla.mozilla.org/show_bug.cgi?id=941749 made window handles in marionette correspond to tabs. Greenlight libraries need to be updated to reflect this. @whimboo, can you provide a pointer to what you think needs to be updated for this?

**Comment by whimboo** [comment]
I filed two bugs to get the right behavior in our tests:

* For chrome windows: https://bugzilla.mozilla.org/show_bug.cgi?id=1121698
* For tabs: https://bugzilla.mozilla.org/show_bug.cgi?id=1121705
