### ISSUE TITLE
Investigate how to cope with backward incompatible changes in Marionette

### ISSUE THREAD

**Issue by whimboo** [mozilla/firefox-ui-tests#8]
Lately a feature has been added to Marionette which [let it return a session uuid](https://bugzilla.mozilla.org/show_bug.cgi?id=1073732). This change only landed for Firefox 36.0a1 and is not backward compatible! So it will cause a lot of trouble for our update tests.

Please check the following example:

We have a Firefox 35.0 release build and QA has to run the update tests to let it update to Firefox 36.0. While the marionette client version we make use of for Firefox 35.0 will work with the corresponding Firefox 35.0 build, it will fail with Firefox 36.0, which is the version after the successful update. As result the update tests will fail.

So here some questions:
* When we have branches in this repository for all versions of Firefox, which version of Marionette should be used? I assume it will be the latest version on the specific branch as released to pypi. Means each branch will have its own Marionette version?

* If we detect broken behavior in Marionette on older branches, how big is the possibility to get a fix for it? This would be important if we run into a blocker for QA.

* I don't see a way in using different versions of Marionette for update tests, but anyone with an idea how to be able to solve the above incompatibility problem? With Mozmill we had the same code working for all branches. So we never stepped into that problem

@AutomatedTester, @ahal, @chmanchester, @jonallengriffin anyone with an idea and feedback?

**Comment by whimboo** [comment]
For me that sounds fine. But lets get feedback from @AutomatedTester too.

**Comment by AutomatedTester** [comment]
We only discussed what would happen to the transport layer and that is the only changes that need to be done. If tests need updating then they will need to be uplifted to the relevant places.

**Comment by whimboo** [comment]
That's right. So I think nothing more has to be discussed here. Once we have those separate packages for marionette client and runner, we can check how it works.
